// <auto-generated />
using System;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.model.Book", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book_author");

                    b.Property<string>("available")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book_to_buy");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book_genre");

                    b.Property<int>("lentQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("book_lent_quantity");

                    b.Property<int>("quantity")
                        .HasColumnType("integer")
                        .HasColumnName("book_quantity");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book_title");

                    b.HasKey("id");

                    b.ToTable("book");
                });
#pragma warning restore 612, 618
        }
    }
}
